In [1]:
!pip install numpy
!pip install pandas
!pip install scikit-learn

Requirement already satisfied: numpy in c:\users\acer\appdata\local\programs\python\python313\lib\site-packages (2.1.2)
Requirement already satisfied: pandas in c:\users\acer\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\acer\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\acer\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\acer\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\acer\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\acer\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Collecting scikit-learn
  Using cached scikit_learn-1.5.2-cp313-cp313-win_amd64.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.19.5 in c:\users\acer\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.1.2)
Collecting scipy>=1.6.0 (from scikit-learn)
  Using cached scipy-1.14.1-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.2.0 (from scikit-learn)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.5.2-cp313-cp313-win_amd64.whl (11.0 MB)
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Downloading scipy-1.14.1-cp313-cp313-win_amd64.whl (44.5 MB)
   ---------------------------------------- 0.0/44.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/44.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/44.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/44.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/44.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/44.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/44.5 MB ? eta -:--:--
   ---------------------------------------- 0.5/44.5 MB 438.9 kB/s eta 0:01:41
   ---------------------------------------- 0.5/44.5 MB 438.9 kB/s eta 0:01:41
   ---------------------------------------- 0.5/44.5 MB 438.9 kB/s eta 0:01:41
    --------------------------------------- 0.8/44.5 MB 425.6 kB/s eta 0:01:43
    --------------------------------------- 0.8/44.5 MB 425.6 kB/s eta 0:01:43
    --------------------------------------- 0.8/44.5 MB 425.6 kB/s eta 0:01:43
    --------------------------------------- 1.0/44.5 MB 426.1 kB/s eta 0:01:42
    --------------------------------------- 1.0/44.5 MB 426.1 kB/s eta 0:01:42
    --------------------------------------- 1.0/44.5 MB 426.1 kB/s eta 0:01:42
    --------------------------------------- 1.0/44.5 MB 426.1 kB/s eta 0:01:42
   - -------------------------------------- 1.3/44.5 MB 376.0 kB/s eta 0:01:55
   - -------------------------------------- 1.3/44.5 MB 376.0 kB/s eta 0:01:55
   - -------------------------------------- 1.6/44.5 MB 420.0 kB/s eta 0:01:43
   - -------------------------------------- 1.6/44.5 MB 420.0 kB/s eta 0:01:43
   - -------------------------------------- 1.6/44.5 MB 420.0 kB/s eta 0:01:43
   - -------------------------------------- 1.6/44.5 MB 420.0 kB/s eta 0:01:43
   - -------------------------------------- 1.8/44.5 MB 388.6 kB/s eta 0:01:50
   - -------------------------------------- 1.8/44.5 MB 388.6 kB/s eta 0:01:50
   - -------------------------------------- 1.8/44.5 MB 388.6 kB/s eta 0:01:50
   - -------------------------------------- 2.1/44.5 MB 393.7 kB/s eta 0:01:48
   -- ------------------------------------- 2.4/44.5 MB 421.0 kB/s eta 0:01:41
   -- ------------------------------------- 2.9/44.5 MB 506.6 kB/s eta 0:01:23
   --- ------------------------------------ 3.7/44.5 MB 630.4 kB/s eta 0:01:05
   ---- ----------------------------------- 4.5/44.5 MB 744.0 kB/s eta 0:00:54
   ---- ----------------------------------- 5.2/44.5 MB 849.8 kB/s eta 0:00:47
   ----- ---------------------------------- 6.0/44.5 MB 950.9 kB/s eta 0:00:41
   ------ --------------------------------- 6.8/44.5 MB 1.1 MB/s eta 0:00:36
   ------- -------------------------------- 7.9/44.5 MB 1.2 MB/s eta 0:00:32
   ------- -------------------------------- 7.9/44.5 MB 1.2 MB/s eta 0:00:32
   ------- -------------------------------- 8.1/44.5 MB 1.2 MB/s eta 0:00:32
   ------- -------------------------------- 8.4/44.5 MB 1.2 MB/s eta 0:00:32
   ------- -------------------------------- 8.4/44.5 MB 1.2 MB/s eta 0:00:32
   -------- ------------------------------- 8.9/44.5 MB 1.2 MB/s eta 0:00:31
   -------- ------------------------------- 9.4/44.5 MB 1.2 MB/s eta 0:00:30
   -------- ------------------------------- 9.7/44.5 MB 1.2 MB/s eta 0:00:29
   --------- ------------------------------ 10.5/44.5 MB 1.3 MB/s eta 0:00:27
   --------- ------------------------------ 10.7/44.5 MB 1.3 MB/s eta 0:00:27
   ---------- ----------------------------- 11.5/44.5 MB 1.3 MB/s eta 0:00:25
   ---------- ----------------------------- 11.8/44.5 MB 1.3 MB/s eta 0:00:25
   ----------- ---------------------------- 12.6/44.5 MB 1.4 MB/s eta 0:00:24
   ------------ --------------------------- 13.4/44.5 MB 1.4 MB/s eta 0:00:22
   ------------ --------------------------- 13.6/44.5 MB 1.4 MB/s eta 0:00:22
   ------------ --------------------------- 14.4/44.5 MB 1.5 MB/s eta 0:00:21
   ------------ --------------------------- 14.4/44.5 MB 1.5 MB/s eta 0:00:21
   ------------- -------------------------- 15.2/44.5 MB 1.5 MB/s eta 0:00:20
   -------------- ------------------------- 16.0/44.5 MB 1.5 MB/s eta 0:00:19
   -------------- ------------------------- 16.5/44.5 MB 1.6 MB/s eta 0:00:18
   --------------- ------------------------ 17.3/44.5 MB 1.6 MB/s eta 0:00:17
   ---------------- ----------------------- 17.8/44.5 MB 1.6 MB/s eta 0:00:17
   ---------------- ----------------------- 18.6/44.5 MB 1.7 MB/s eta 0:00:16
   ----------------- ---------------------- 19.7/44.5 MB 1.7 MB/s eta 0:00:15
   ------------------ --------------------- 20.4/44.5 MB 1.8 MB/s eta 0:00:14
   ------------------- -------------------- 21.2/44.5 MB 1.8 MB/s eta 0:00:13
   ------------------- -------------------- 22.0/44.5 MB 1.8 MB/s eta 0:00:13
   -------------------- ------------------- 22.8/44.5 MB 1.9 MB/s eta 0:00:12
   --------------------- ------------------ 23.6/44.5 MB 1.9 MB/s eta 0:00:11
   --------------------- ------------------ 24.4/44.5 MB 1.9 MB/s eta 0:00:11
   ---------------------- ----------------- 25.2/44.5 MB 2.0 MB/s eta 0:00:10
   ----------------------- ---------------- 26.0/44.5 MB 2.0 MB/s eta 0:00:10
   ----------------------- ---------------- 26.5/44.5 MB 2.0 MB/s eta 0:00:09
   ------------------------ --------------- 27.5/44.5 MB 2.0 MB/s eta 0:00:09
   ------------------------- -------------- 28.6/44.5 MB 2.1 MB/s eta 0:00:08
   -------------------------- ------------- 29.9/44.5 MB 2.2 MB/s eta 0:00:07
   --------------------------- ------------ 30.9/44.5 MB 2.2 MB/s eta 0:00:07
   ---------------------------- ----------- 31.7/44.5 MB 2.2 MB/s eta 0:00:06
   ----------------------------- ---------- 32.5/44.5 MB 2.3 MB/s eta 0:00:06
   ----------------------------- ---------- 33.0/44.5 MB 2.3 MB/s eta 0:00:06
   ------------------------------ --------- 33.8/44.5 MB 2.3 MB/s eta 0:00:05
   ------------------------------- -------- 34.9/44.5 MB 2.3 MB/s eta 0:00:05
   ------------------------------- -------- 35.4/44.5 MB 2.3 MB/s eta 0:00:04
   -------------------------------- ------- 35.9/44.5 MB 2.3 MB/s eta 0:00:04
   --------------------------------- ------ 37.0/44.5 MB 2.4 MB/s eta 0:00:04
   ---------------------------------- ----- 38.0/44.5 MB 2.4 MB/s eta 0:00:03
   ---------------------------------- ----- 38.5/44.5 MB 2.4 MB/s eta 0:00:03
   ----------------------------------- ---- 39.6/44.5 MB 2.4 MB/s eta 0:00:03
   ------------------------------------ --- 40.1/44.5 MB 2.4 MB/s eta 0:00:02
   ------------------------------------ --- 40.9/44.5 MB 2.4 MB/s eta 0:00:02
   ------------------------------------- -- 41.7/44.5 MB 2.5 MB/s eta 0:00:02
   ------------------------------------- -- 42.2/44.5 MB 2.5 MB/s eta 0:00:01
   -------------------------------------- - 42.5/44.5 MB 2.5 MB/s eta 0:00:01
   -------------------------------------- - 43.0/44.5 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  43.8/44.5 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  44.3/44.5 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------- 44.5/44.5 MB 2.5 MB/s eta 0:00:00
Downloading threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.4.2 scikit-learn-1.5.2 scipy-1.14.1 threadpoolctl-3.5.0

In [2]:
import numpy as np

import pandas as pd

In [3]:
#reading datasets
books=pd.read_csv('C:/Users/acer/Desktop/Data_set/dataset/Books.csv')
ratings=pd.read_csv('C:/Users/acer/Desktop/Data_set/dataset/ratings.csv')
users=pd.read_csv('C:/Users/acer/Desktop/Data_set/dataset/users.csv')

In [4]:
users.head()

,user id,name,age,gender,liked categories
0,1,Udari,25-34,Female,"Novels,Sci-Fi,Adventure"
1,2,Isuru,25-34,Male,"Translations,Novels,Adventure,Child"
2,3,Buddhi Ekanayake,25-34,Male,"Spy,Novels,Crime"
3,4,R.P.D.Lakshan,18-24,Male,"Mystrey,Biographie"
4,5,Dileka,18-24,Female,"Novels,Sci-Fi,Adventure"

In [5]:
ratings.head()

   User-ID           ISBN  Ratings
0        1  9789551319182        5
1        1  9789550980239        5
2        2      95521033X        5
3        4  9789558415436        5
4        5  9789556971996        5

In [6]:
books.head()

,Book_ID,Book name si,Book_Title,Category,Author,ISBN,Total ratings
0,1,???? ????,Guru geethaya,"Translations,Novels",Chingiz Aitmatov,9789551319182,5.0
1,2,??? ?????,Dandumonaraya,Novels,Martin Wickramasinghe,9789558415252,4.0
2,3,???? ??? ????????,May mara prasangaya,Novels,Mahinda prasad masimbula,9786245594252,4.0
3,4,??????????,Manikkawatha,Novels,Mahinda prasad masimbula,9789550980239,4.3
4,5,??? ?????,Chaura Rajina,"Biographie,Novels",Victor ivan,9551468031,3.0

In [7]:
print(books.shape)
print(ratings.shape)
print(users.shape)

(185, 7)
(329, 3)
(39, 5)

In [8]:
books.isnull().sum()

Book_ID          0
Book name si     0
Book_Title       0
Category         0
Author           0
ISBN             0
Total ratings    0
dtype: int64

In [9]:
users.isnull().sum()

user id             0
name                0
age                 0
gender              0
liked categories    0
dtype: int64

In [10]:
ratings.isnull().sum()

User-ID    0
ISBN       0
Ratings    0
dtype: int64

In [11]:
books.duplicated().sum()

np.int64(0)

In [12]:
ratings.duplicated().sum()

np.int64(2)

In [13]:
users.duplicated().sum()

np.int64(0)

In [14]:
books.ISBN

0      9789551319182
1      9789558415252
2      9786245594252
3      9789550980239
4         9551468031
           ...
180    9789557450001
181    9786242041810
182    9786245941957
183    9789553131201
184    9786246451752
Name: ISBN, Length: 185, dtype: object

## Popularity Based Recommender System

In [15]:
ratings_with_name = ratings.merge(books,on='ISBN')
ratings_with_name

,User-ID,ISBN,Ratings,Book_ID,Book name si,Book_Title,Category,Author,Total ratings
0,1,9789551319182,5,1,???? ????,Guru geethaya,"Translations,Novels",Chingiz Aitmatov,5.0
1,1,9789550980239,5,4,??????????,Manikkawatha,Novels,Mahinda prasad masimbula,4.3
2,2,95521033X,5,7,????????,Baeddegama,Novels,Leonard Woolf,5.0
3,4,9789558415436,5,15,?????????,Gamperaliya,"Novels,Fiction",Martin Wickramasinghe,5.0
4,5,9789556971996,5,20,??? ???,Rathu ahasa,Novels,Sakunthala Kumarihami,5.0
...,...,...,...,...,...,...,...,...,...
340,15,9786245594252,4,3,???? ??? ????????,May mara prasangaya,Novels,Mahinda prasad masimbula,4.0
341,14,9786245594252,3,3,???? ??? ????????,May mara prasangaya,Novels,Mahinda prasad masimbula,4.0
342,16,9789552130458,1,131,???? ????,Bahina kalawa,Short stories,E.R. sarachchandra,5.0
343,13,9789552130458,1,131,???? ????,Bahina kalawa,Short stories,E.R. sarachchandra,5.0
344,17,9789552130458,5,131,???? ????,Bahina kalawa,Short stories,E.R. sarachchandra,5.0

In [16]:
num_rating_df = ratings_with_name.groupby('ISBN').count()['Ratings'].reset_index()
num_rating_df

              ISBN  Ratings
0       6249468706        1
1       9551468031        1
2        95521033X        4
3       9553132588        1
4       9554690002        1
..             ...      ...
175  9789559520078        4
176  9789559535690        1
177  9789559593099        4
178  9789559682849        1
179  9789559758709        1

[180 rows x 2 columns]

In [17]:
num_rating_df.rename(columns={'Ratings':'num_ratings'},inplace=True)
num_rating_df

              ISBN  num_ratings
0       6249468706            1
1       9551468031            1
2        95521033X            4
3       9553132588            1
4       9554690002            1
..             ...          ...
175  9789559520078            4
176  9789559535690            1
177  9789559593099            4
178  9789559682849            1
179  9789559758709            1

[180 rows x 2 columns]

In [18]:
print(ratings_with_name['Ratings'].unique())

[5 4 3 2 1]

In [19]:
ratings_with_name['Ratings'] = pd.to_numeric(ratings_with_name['Ratings'], errors='coerce')

In [20]:
avg_rating_df = ratings_with_name.groupby('ISBN')['Ratings'].mean().reset_index()

In [21]:
avg_rating_df.rename(columns={'Ratings': 'avg_rating'}, inplace=True)

In [22]:
avg_rating_df

              ISBN  avg_rating
0       6249468706        3.00
1       9551468031        3.00
2        95521033X        4.25
3       9553132588        1.00
4       9554690002        3.00
..             ...         ...
175  9789559520078        4.25
176  9789559535690        3.00
177  9789559593099        4.00
178  9789559682849        4.00
179  9789559758709        2.00

[180 rows x 2 columns]

In [23]:
popular_df = num_rating_df.merge(avg_rating_df,on='ISBN')
popular_df

              ISBN  num_ratings  avg_rating
0       6249468706            1        3.00
1       9551468031            1        3.00
2        95521033X            4        4.25
3       9553132588            1        1.00
4       9554690002            1        3.00
..             ...          ...         ...
175  9789559520078            4        4.25
176  9789559535690            1        3.00
177  9789559593099            4        4.00
178  9789559682849            1        4.00
179  9789559758709            1        2.00

[180 rows x 3 columns]

In [24]:
popular_df = popular_df[popular_df['num_ratings']>=250].sort_values('avg_rating',ascending=False).head(50)

In [25]:
popular_df = popular_df[popular_df['num_ratings']>=250].sort_values('avg_rating',ascending=False).head(50)

In [26]:
popular_df

Empty DataFrame
Columns: [ISBN, num_ratings, avg_rating]
Index: []

In [27]:
popular_df = popular_df.merge(books,on='ISBN').drop_duplicates('ISBN')[['ISBN','Book_Title','num_ratings','avg_rating']]

In [28]:
popular_df

Empty DataFrame
Columns: [ISBN, Book_Title, num_ratings, avg_rating]
Index: []

## Collaborative Filtering Based Recommender System

In [40]:
ratings_with_name

,User-ID,ISBN,Ratings,Book_ID,Book name si,Book_Title,Category,Author,Total ratings
0,1,9789551319182,5,1,???? ????,Guru geethaya,"Translations,Novels",Chingiz Aitmatov,5.0
1,1,9789550980239,5,4,??????????,Manikkawatha,Novels,Mahinda prasad masimbula,4.3
2,2,95521033X,5,7,????????,Baeddegama,Novels,Leonard Woolf,5.0
3,4,9789558415436,5,15,?????????,Gamperaliya,"Novels,Fiction",Martin Wickramasinghe,5.0
4,5,9789556971996,5,20,??? ???,Rathu ahasa,Novels,Sakunthala Kumarihami,5.0
...,...,...,...,...,...,...,...,...,...
340,15,9786245594252,4,3,???? ??? ????????,May mara prasangaya,Novels,Mahinda prasad masimbula,4.0
341,14,9786245594252,3,3,???? ??? ????????,May mara prasangaya,Novels,Mahinda prasad masimbula,4.0
342,16,9789552130458,1,131,???? ????,Bahina kalawa,Short stories,E.R. sarachchandra,5.0
343,13,9789552130458,1,131,???? ????,Bahina kalawa,Short stories,E.R. sarachchandra,5.0
344,17,9789552130458,5,131,???? ????,Bahina kalawa,Short stories,E.R. sarachchandra,5.0

In [41]:
x = ratings_with_name.groupby('User-ID').count()['Ratings'] > 0
padhe_likhe_users = x[x].index

x

User-ID
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
10    True
11    True
12    True
13    True
14    True
15    True
16    True
17    True
18    True
19    True
20    True
21    True
22    True
23    True
24    True
25    True
26    True
27    True
28    True
29    True
30    True
31    True
32    True
33    True
34    True
35    True
36    True
37    True
38    True
39    True
Name: Ratings, dtype: bool

In [42]:
filtered_rating = ratings_with_name[ratings_with_name['User-ID'].isin(padhe_likhe_users)]
filtered_rating

,User-ID,ISBN,Ratings,Book_ID,Book name si,Book_Title,Category,Author,Total ratings
0,1,9789551319182,5,1,???? ????,Guru geethaya,"Translations,Novels",Chingiz Aitmatov,5.0
1,1,9789550980239,5,4,??????????,Manikkawatha,Novels,Mahinda prasad masimbula,4.3
2,2,95521033X,5,7,????????,Baeddegama,Novels,Leonard Woolf,5.0
3,4,9789558415436,5,15,?????????,Gamperaliya,"Novels,Fiction",Martin Wickramasinghe,5.0
4,5,9789556971996,5,20,??? ???,Rathu ahasa,Novels,Sakunthala Kumarihami,5.0
...,...,...,...,...,...,...,...,...,...
340,15,9786245594252,4,3,???? ??? ????????,May mara prasangaya,Novels,Mahinda prasad masimbula,4.0
341,14,9786245594252,3,3,???? ??? ????????,May mara prasangaya,Novels,Mahinda prasad masimbula,4.0
342,16,9789552130458,1,131,???? ????,Bahina kalawa,Short stories,E.R. sarachchandra,5.0
343,13,9789552130458,1,131,???? ????,Bahina kalawa,Short stories,E.R. sarachchandra,5.0
344,17,9789552130458,5,131,???? ????,Bahina kalawa,Short stories,E.R. sarachchandra,5.0

In [46]:
y = filtered_rating.groupby('Book_Title').count()['Ratings']>=1
famous_books = y[y].index
famous_books

Index(['ABC Mini marum', 'Aggala dansela', 'Agrawe maha nidanaya',
       'Allapu gedara', 'Almond', 'Amba Yahaluwo', 'Amma', 'Amuthu dige',
       'Anagathe loke wate', 'Ape gama',
       ...
       'Waththa pahala sumithuro', 'Wel patin wesunu muhune abhirahasa',
       'Wilthera ketikatha sangrahaya', 'Wiyali kopul',
       'Wyakarana guruwaraya sandhi', 'Yuwathiyakage premaya', 'kalu sihinaya',
       'kaluwarayaa', 'kolaba pansala', 'wish'],
      dtype='object', name='Book_Title', length=180)

In [47]:
final_ratings = filtered_rating[filtered_rating['Book_Title'].isin(famous_books)]
final_ratings

,User-ID,ISBN,Ratings,Book_ID,Book name si,Book_Title,Category,Author,Total ratings
0,1,9789551319182,5,1,???? ????,Guru geethaya,"Translations,Novels",Chingiz Aitmatov,5.0
1,1,9789550980239,5,4,??????????,Manikkawatha,Novels,Mahinda prasad masimbula,4.3
2,2,95521033X,5,7,????????,Baeddegama,Novels,Leonard Woolf,5.0
3,4,9789558415436,5,15,?????????,Gamperaliya,"Novels,Fiction",Martin Wickramasinghe,5.0
4,5,9789556971996,5,20,??? ???,Rathu ahasa,Novels,Sakunthala Kumarihami,5.0
...,...,...,...,...,...,...,...,...,...
340,15,9786245594252,4,3,???? ??? ????????,May mara prasangaya,Novels,Mahinda prasad masimbula,4.0
341,14,9786245594252,3,3,???? ??? ????????,May mara prasangaya,Novels,Mahinda prasad masimbula,4.0
342,16,9789552130458,1,131,???? ????,Bahina kalawa,Short stories,E.R. sarachchandra,5.0
343,13,9789552130458,1,131,???? ????,Bahina kalawa,Short stories,E.R. sarachchandra,5.0
344,17,9789552130458,5,131,???? ????,Bahina kalawa,Short stories,E.R. sarachchandra,5.0

In [49]:
pt = final_ratings.pivot_table(index='Book_Title',columns='User-ID',values='Ratings')
pt

User-ID,1,2,3,4,5,6,7,8,9,10,...,30,31,32,33,34,35,36,37,38,39
Book_Title,,,,,,,,,,,,,,,,,,,,,
ABC Mini marum,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Aggala dansela,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN
Agrawe maha nidanaya,NaN,NaN,NaN,NaN,2.0,4.0,5.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Allapu gedara,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Almond,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Yuwathiyakage premaya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
kalu sihinaya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
kaluwarayaa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
kolaba pansala,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wish,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
pt.fillna(0,inplace=True)

In [51]:
pt

User-ID,1,2,3,4,5,6,7,8,9,10,...,30,31,32,33,34,35,36,37,38,39
Book_Title,,,,,,,,,,,,,,,,,,,,,
ABC Mini marum,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Aggala dansela,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0
Agrawe maha nidanaya,0.0,0.0,0.0,0.0,2.0,4.0,5.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Allapu gedara,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Almond,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Yuwathiyakage premaya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
kalu sihinaya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
kaluwarayaa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
kolaba pansala,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wish,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [52]:
from sklearn.metrics.pairwise import cosine_similarity

In [53]:
similarity_scores = cosine_similarity(pt)

In [54]:
similarity_scores.shape

(180, 180)

In [58]:
def recommend(book_name):
    # index fetch
    index = np.where(pt.index==book_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_scores[index])),key=lambda x:x[1],reverse=True)[1:5]
    
    data = []
    for i in similar_items:
        item = []
        temp_df = books[books['Book_Title'] == pt.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates('Book_Title')['Book_Title'].values))
        item.extend(list(temp_df.drop_duplicates('Book_Title')['Author'].values))
       
        
        data.append(item)
    
    return data

In [59]:
recommend('kaluwarayaa')

[['Bella mage harima age', 'Piyal Udaya Samaraweera'],
 ['Rajawenta giya mahanna', 'Martin Wickramasinghe'],
 ['Waththa pahala sumithuro', 'I.A. Sasiru Yonal Bojitha'],
 ['kaluwarayaa', 'Nuwan thotawaththa']]

In [61]:
pt.index[85]

'Lohitha pareekshanaya'

In [62]:
import pickle
pickle.dump(popular_df,open('popular.pkl','wb'))

In [63]:
books.drop_duplicates('Book_Title')

,Book_ID,Book name si,Book_Title,Category,Author,ISBN,Total ratings
0,1,???? ????,Guru geethaya,"Translations,Novels",Chingiz Aitmatov,9789551319182,5.0
1,2,??? ?????,Dandumonaraya,Novels,Martin Wickramasinghe,9789558415252,4.0
2,3,???? ??? ????????,May mara prasangaya,Novels,Mahinda prasad masimbula,9786245594252,4.0
3,4,??????????,Manikkawatha,Novels,Mahinda prasad masimbula,9789550980239,4.3
4,5,??? ?????,Chaura Rajina,"Biographie,Novels",Victor ivan,9551468031,3.0
...,...,...,...,...,...,...,...
180,183,?????,Chamalee,"Translations,Novels","Siril C.Perera,Karthal Singh Dugal",9789557450001,5.0
181,184,??? ??????,kalu sihinaya,"Translations,Novels",Piyal Panapitiya,9786242041810,3.0
182,185,???? ?????? ?? ????????? ??????,His wesum lu ukussage abirahasa,"Spy,Child,Translations",Dayaa D. Fonseka,9786245941957,4.0
183,186,??????????? ????,Surupiniyage maranaya,"Spy,Translations,Novels",Gayan Sampath Waniganeththi,9789553131201,5.0
184,187,??? ?? ????????,Diya yata wikramaya,"Spy,Translations,Novels",Wasantha Pigera,9786246451752,5.0

In [64]:
pickle.dump(pt,open('pt.pkl','wb'))
pickle.dump(books,open('books.pkl','wb'))
pickle.dump(similarity_scores,open('similarity_scores.pkl','wb'))