In [1]:
!pip install numpy
!pip install pandas
!pip install scikit-learn

Requirement already satisfied: numpy in c:\dev\python\lib\site-packages (1.26.4)

WARNING: Ignoring invalid distribution ~pencv-python-headless (C:\Dev\Python\Lib\site-packages)
WARNING: Ignoring invalid distribution ~pencv-python-headless (C:\Dev\Python\Lib\site-packages)
WARNING: Ignoring invalid distribution ~pencv-python-headless (C:\Dev\Python\Lib\site-packages)

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in c:\dev\python\lib\site-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\dev\python\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\dev\python\lib\site-packages (from pandas) (2022.7.1)
Requirement already satisfied: tzdata>=2022.1 in c:\dev\python\lib\site-packages (from pandas) (2022.7)
Requirement already satisfied: numpy>=1.21.0 in c:\dev\python\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: six>=1.5 in c:\dev\python\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

WARNING: Ignoring invalid distribution ~pencv-python-headless (C:\Dev\Python\Lib\site-packages)
WARNING: Ignoring invalid distribution ~pencv-python-headless (C:\Dev\Python\Lib\site-packages)
WARNING: Ignoring invalid distribution ~pencv-python-headless (C:\Dev\Python\Lib\site-packages)

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: scikit-learn in c:\dev\python\lib\site-packages (1.3.0)
Requirement already satisfied: numpy>=1.17.3 in c:\dev\python\lib\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.5.0 in c:\dev\python\lib\site-packages (from scikit-learn) (1.11.2)
Requirement already satisfied: joblib>=1.1.1 in c:\dev\python\lib\site-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\dev\python\lib\site-packages (from scikit-learn) (3.2.0)

WARNING: Ignoring invalid distribution ~pencv-python-headless (C:\Dev\Python\Lib\site-packages)
WARNING: Ignoring invalid distribution ~pencv-python-headless (C:\Dev\Python\Lib\site-packages)
WARNING: Ignoring invalid distribution ~pencv-python-headless (C:\Dev\Python\Lib\site-packages)

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import numpy as np
import pandas as pd

In [3]:
#reading datasets
books=pd.read_csv('dataset/Books.csv')
ratings=pd.read_csv('dataset/ratings.csv')
users=pd.read_csv('dataset/users.csv')

In [4]:
users.head()

,user id,name,age,gender,liked categories
0,1,Udari,25-34,Female,"Novels,Sci-Fi,Adventure"
1,2,Isuru,25-34,Male,"Translations,Novels,Adventure,Child"
2,3,Buddhi Ekanayake,25-34,Male,"Spy,Novels,Crime"
3,4,R.P.D.Lakshan,18-24,Male,"Mystrey,Biographie"
4,5,Dileka,18-24,Female,"Novels,Sci-Fi,Adventure"

In [5]:
ratings.head()

   User-ID           ISBN  Ratings
0        1  9789551319182        5
1        1  9789550980239        5
2        2      95521033X        5
3        4  9789558415436        5
4        5  9789556971996        5

In [6]:
books.head()

,Book_ID,Book name si,Book_Title,Category,Author,ISBN,Total ratings
0,1,???? ????,Guru geethaya,"Translations,Novels",Chingiz Aitmatov,9789551319182,5.0
1,2,??? ?????,Dandumonaraya,Novels,Martin Wickramasinghe,9789558415252,4.0
2,3,???? ??? ????????,May mara prasangaya,Novels,Mahinda prasad masimbula,9786245594252,4.0
3,4,??????????,Manikkawatha,Novels,Mahinda prasad masimbula,9789550980239,4.3
4,5,??? ?????,Chaura Rajina,"Biographie,Novels",Victor ivan,9551468031,3.0

In [7]:
print(books.shape)
print(ratings.shape)
print(users.shape)

(185, 7)
(329, 3)
(39, 5)

In [8]:
books.isnull().sum()

Book_ID          0
Book name si     0
Book_Title       0
Category         0
Author           0
ISBN             0
Total ratings    0
dtype: int64

In [9]:
users.isnull().sum()

user id             0
name                0
age                 0
gender              0
liked categories    0
dtype: int64

In [10]:
ratings.isnull().sum()

User-ID    0
ISBN       0
Ratings    0
dtype: int64

In [11]:
books.duplicated().sum()

0

In [12]:
ratings.duplicated().sum()

2

In [13]:
users.duplicated().sum()

0

In [14]:
books.ISBN

0      9789551319182
1      9789558415252
2      9786245594252
3      9789550980239
4         9551468031
           ...
180    9789557450001
181    9786242041810
182    9786245941957
183    9789553131201
184    9786246451752
Name: ISBN, Length: 185, dtype: object

## Popularity Based Recommender System

In [15]:
ratings_with_name = ratings.merge(books,on='ISBN')
ratings_with_name

,User-ID,ISBN,Ratings,Book_ID,Book name si,Book_Title,Category,Author,Total ratings
0,1,9789551319182,5,1,???? ????,Guru geethaya,"Translations,Novels",Chingiz Aitmatov,5.0
1,2,9789551319182,4,1,???? ????,Guru geethaya,"Translations,Novels",Chingiz Aitmatov,5.0
2,3,9789551319182,3,1,???? ????,Guru geethaya,"Translations,Novels",Chingiz Aitmatov,5.0
3,1,9789550980239,5,4,??????????,Manikkawatha,Novels,Mahinda prasad masimbula,4.3
4,2,9789550980239,4,4,??????????,Manikkawatha,Novels,Mahinda prasad masimbula,4.3
...,...,...,...,...,...,...,...,...,...
340,22,9786245710942,1,100,??????? ?????,Bawanthara bandana,Novels,Thilaka kudahetti,1.0
341,29,9789245664931,1,135,????? ????,Jaawai mamai,"Translations,Child",Shrilani fernando,1.0
342,31,9786246451660,1,146,????? ????????? ??? ?????? 9 - ????????? ?? ????,Endi blyton 9 athurudahan wu balala,"Translations,Child",Kumara siriwardana,1.0
343,32,9786245713752,1,150,?????? ???? ??? - ???????? ??????? ???? ????? ...,Anagathe loke wate,Child,Nuwan thotawaththa,1.0
344,34,9786245519606,1,160,???? ????? ??????,Holly mawathe abirahasa,"Child,Spy",Melani Amarathunga,1.0

In [16]:
num_rating_df = ratings_with_name.groupby('ISBN').count()['Ratings'].reset_index()
num_rating_df

              ISBN  Ratings
0       6249468706        1
1       9551468031        1
2        95521033X        4
3       9553132588        1
4       9554690002        1
..             ...      ...
175  9789559520078        4
176  9789559535690        1
177  9789559593099        4
178  9789559682849        1
179  9789559758709        1

[180 rows x 2 columns]

In [17]:
num_rating_df.rename(columns={'Ratings':'num_ratings'},inplace=True)
num_rating_df

              ISBN  num_ratings
0       6249468706            1
1       9551468031            1
2        95521033X            4
3       9553132588            1
4       9554690002            1
..             ...          ...
175  9789559520078            4
176  9789559535690            1
177  9789559593099            4
178  9789559682849            1
179  9789559758709            1

[180 rows x 2 columns]

In [18]:
print(ratings_with_name['Ratings'].unique())

[5 4 3 2 1]

In [19]:
ratings_with_name['Ratings'] = pd.to_numeric(ratings_with_name['Ratings'], errors='coerce')

In [20]:
avg_rating_df = ratings_with_name.groupby('ISBN')['Ratings'].mean().reset_index()

In [21]:
avg_rating_df.rename(columns={'Ratings': 'avg_rating'}, inplace=True)

In [22]:
avg_rating_df

              ISBN  avg_rating
0       6249468706        3.00
1       9551468031        3.00
2        95521033X        4.25
3       9553132588        1.00
4       9554690002        3.00
..             ...         ...
175  9789559520078        4.25
176  9789559535690        3.00
177  9789559593099        4.00
178  9789559682849        4.00
179  9789559758709        2.00

[180 rows x 2 columns]

In [23]:
popular_df = num_rating_df.merge(avg_rating_df,on='ISBN')
popular_df

              ISBN  num_ratings  avg_rating
0       6249468706            1        3.00
1       9551468031            1        3.00
2        95521033X            4        4.25
3       9553132588            1        1.00
4       9554690002            1        3.00
..             ...          ...         ...
175  9789559520078            4        4.25
176  9789559535690            1        3.00
177  9789559593099            4        4.00
178  9789559682849            1        4.00
179  9789559758709            1        2.00

[180 rows x 3 columns]

In [24]:
popular_df = popular_df[popular_df['num_ratings']>=250].sort_values('avg_rating',ascending=False).head(50)

In [25]:
popular_df = popular_df[popular_df['num_ratings']>=250].sort_values('avg_rating',ascending=False).head(50)

In [26]:
popular_df

Empty DataFrame
Columns: [ISBN, num_ratings, avg_rating]
Index: []

In [27]:
popular_df = popular_df.merge(books,on='ISBN').drop_duplicates('ISBN')[['ISBN','Book_Title','num_ratings','avg_rating']]

In [28]:
popular_df

Empty DataFrame
Columns: [ISBN, Book_Title, num_ratings, avg_rating]
Index: []

## Collaborative Filtering Based Recommender System

In [29]:
ratings_with_name

,User-ID,ISBN,Ratings,Book_ID,Book name si,Book_Title,Category,Author,Total ratings
0,1,9789551319182,5,1,???? ????,Guru geethaya,"Translations,Novels",Chingiz Aitmatov,5.0
1,2,9789551319182,4,1,???? ????,Guru geethaya,"Translations,Novels",Chingiz Aitmatov,5.0
2,3,9789551319182,3,1,???? ????,Guru geethaya,"Translations,Novels",Chingiz Aitmatov,5.0
3,1,9789550980239,5,4,??????????,Manikkawatha,Novels,Mahinda prasad masimbula,4.3
4,2,9789550980239,4,4,??????????,Manikkawatha,Novels,Mahinda prasad masimbula,4.3
...,...,...,...,...,...,...,...,...,...
340,22,9786245710942,1,100,??????? ?????,Bawanthara bandana,Novels,Thilaka kudahetti,1.0
341,29,9789245664931,1,135,????? ????,Jaawai mamai,"Translations,Child",Shrilani fernando,1.0
342,31,9786246451660,1,146,????? ????????? ??? ?????? 9 - ????????? ?? ????,Endi blyton 9 athurudahan wu balala,"Translations,Child",Kumara siriwardana,1.0
343,32,9786245713752,1,150,?????? ???? ??? - ???????? ??????? ???? ????? ...,Anagathe loke wate,Child,Nuwan thotawaththa,1.0
344,34,9786245519606,1,160,???? ????? ??????,Holly mawathe abirahasa,"Child,Spy",Melani Amarathunga,1.0

In [30]:
x = ratings_with_name.groupby('User-ID').count()['Ratings'] > 0
padhe_likhe_users = x[x].index
x

User-ID
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
10    True
11    True
12    True
13    True
14    True
15    True
16    True
17    True
18    True
19    True
20    True
21    True
22    True
23    True
24    True
25    True
26    True
27    True
28    True
29    True
30    True
31    True
32    True
33    True
34    True
35    True
36    True
37    True
38    True
39    True
Name: Ratings, dtype: bool

In [31]:
filtered_rating = ratings_with_name[ratings_with_name['User-ID'].isin(padhe_likhe_users)]
filtered_rating

,User-ID,ISBN,Ratings,Book_ID,Book name si,Book_Title,Category,Author,Total ratings
0,1,9789551319182,5,1,???? ????,Guru geethaya,"Translations,Novels",Chingiz Aitmatov,5.0
1,2,9789551319182,4,1,???? ????,Guru geethaya,"Translations,Novels",Chingiz Aitmatov,5.0
2,3,9789551319182,3,1,???? ????,Guru geethaya,"Translations,Novels",Chingiz Aitmatov,5.0
3,1,9789550980239,5,4,??????????,Manikkawatha,Novels,Mahinda prasad masimbula,4.3
4,2,9789550980239,4,4,??????????,Manikkawatha,Novels,Mahinda prasad masimbula,4.3
...,...,...,...,...,...,...,...,...,...
340,22,9786245710942,1,100,??????? ?????,Bawanthara bandana,Novels,Thilaka kudahetti,1.0
341,29,9789245664931,1,135,????? ????,Jaawai mamai,"Translations,Child",Shrilani fernando,1.0
342,31,9786246451660,1,146,????? ????????? ??? ?????? 9 - ????????? ?? ????,Endi blyton 9 athurudahan wu balala,"Translations,Child",Kumara siriwardana,1.0
343,32,9786245713752,1,150,?????? ???? ??? - ???????? ??????? ???? ????? ...,Anagathe loke wate,Child,Nuwan thotawaththa,1.0
344,34,9786245519606,1,160,???? ????? ??????,Holly mawathe abirahasa,"Child,Spy",Melani Amarathunga,1.0

In [32]:
y = filtered_rating.groupby('Book_Title').count()['Ratings']>=1
famous_books = y[y].index
famous_books

Index(['ABC Mini marum', 'Aggala dansela', 'Agrawe maha nidanaya',
       'Allapu gedara', 'Almond', 'Amba Yahaluwo', 'Amma', 'Amuthu dige',
       'Anagathe loke wate', 'Ape gama',
       ...
       'Waththa pahala sumithuro', 'Wel patin wesunu muhune abhirahasa',
       'Wilthera ketikatha sangrahaya', 'Wiyali kopul',
       'Wyakarana guruwaraya sandhi', 'Yuwathiyakage premaya', 'kalu sihinaya',
       'kaluwarayaa', 'kolaba pansala', 'wish'],
      dtype='object', name='Book_Title', length=180)

In [33]:
final_ratings = filtered_rating[filtered_rating['Book_Title'].isin(famous_books)]
final_ratings

,User-ID,ISBN,Ratings,Book_ID,Book name si,Book_Title,Category,Author,Total ratings
0,1,9789551319182,5,1,???? ????,Guru geethaya,"Translations,Novels",Chingiz Aitmatov,5.0
1,2,9789551319182,4,1,???? ????,Guru geethaya,"Translations,Novels",Chingiz Aitmatov,5.0
2,3,9789551319182,3,1,???? ????,Guru geethaya,"Translations,Novels",Chingiz Aitmatov,5.0
3,1,9789550980239,5,4,??????????,Manikkawatha,Novels,Mahinda prasad masimbula,4.3
4,2,9789550980239,4,4,??????????,Manikkawatha,Novels,Mahinda prasad masimbula,4.3
...,...,...,...,...,...,...,...,...,...
340,22,9786245710942,1,100,??????? ?????,Bawanthara bandana,Novels,Thilaka kudahetti,1.0
341,29,9789245664931,1,135,????? ????,Jaawai mamai,"Translations,Child",Shrilani fernando,1.0
342,31,9786246451660,1,146,????? ????????? ??? ?????? 9 - ????????? ?? ????,Endi blyton 9 athurudahan wu balala,"Translations,Child",Kumara siriwardana,1.0
343,32,9786245713752,1,150,?????? ???? ??? - ???????? ??????? ???? ????? ...,Anagathe loke wate,Child,Nuwan thotawaththa,1.0
344,34,9786245519606,1,160,???? ????? ??????,Holly mawathe abirahasa,"Child,Spy",Melani Amarathunga,1.0

In [34]:
pt = final_ratings.pivot_table(index='Book_Title',columns='User-ID',values='Ratings')
pt

User-ID,1,2,3,4,5,6,7,8,9,10,...,30,31,32,33,34,35,36,37,38,39
Book_Title,,,,,,,,,,,,,,,,,,,,,
ABC Mini marum,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Aggala dansela,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN
Agrawe maha nidanaya,NaN,NaN,NaN,NaN,2.0,4.0,5.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Allapu gedara,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Almond,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Yuwathiyakage premaya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
kalu sihinaya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
kaluwarayaa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
kolaba pansala,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wish,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
pt.fillna(0,inplace=True)

In [36]:
pt

User-ID,1,2,3,4,5,6,7,8,9,10,...,30,31,32,33,34,35,36,37,38,39
Book_Title,,,,,,,,,,,,,,,,,,,,,
ABC Mini marum,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Aggala dansela,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0
Agrawe maha nidanaya,0.0,0.0,0.0,0.0,2.0,4.0,5.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Allapu gedara,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Almond,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Yuwathiyakage premaya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
kalu sihinaya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
kaluwarayaa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
kolaba pansala,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wish,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [37]:
from sklearn.metrics.pairwise import cosine_similarity

In [38]:
similarity_scores = cosine_similarity(pt)

In [39]:
similarity_scores.shape

(180, 180)

In [40]:
def recommend(book_name):
    # index fetch
    index = np.where(pt.index==book_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_scores[index])),key=lambda x:x[1],reverse=True)[1:5]
    
    data = []
    for i in similar_items:
        item = []
        temp_df = books[books['Book_Title'] == pt.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates('Book_Title')['Book_Title'].values))
        item.extend(list(temp_df.drop_duplicates('Book_Title')['Author'].values))
       
        
        data.append(item)
    
    return data

In [41]:
recommend('kaluwarayaa')

[['Bella mage harima age', 'Piyal Udaya Samaraweera'],
 ['Rajawenta giya mahanna', 'Martin Wickramasinghe'],
 ['Waththa pahala sumithuro', 'I.A. Sasiru Yonal Bojitha'],
 ['kaluwarayaa', 'Nuwan thotawaththa']]

In [42]:
pt.index[85]

'Lohitha pareekshanaya'

In [43]:
import pickle
pickle.dump(popular_df,open('popular.pkl','wb'))

In [44]:
books.drop_duplicates('Book_Title')

,Book_ID,Book name si,Book_Title,Category,Author,ISBN,Total ratings
0,1,???? ????,Guru geethaya,"Translations,Novels",Chingiz Aitmatov,9789551319182,5.0
1,2,??? ?????,Dandumonaraya,Novels,Martin Wickramasinghe,9789558415252,4.0
2,3,???? ??? ????????,May mara prasangaya,Novels,Mahinda prasad masimbula,9786245594252,4.0
3,4,??????????,Manikkawatha,Novels,Mahinda prasad masimbula,9789550980239,4.3
4,5,??? ?????,Chaura Rajina,"Biographie,Novels",Victor ivan,9551468031,3.0
...,...,...,...,...,...,...,...
180,183,?????,Chamalee,"Translations,Novels","Siril C.Perera,Karthal Singh Dugal",9789557450001,5.0
181,184,??? ??????,kalu sihinaya,"Translations,Novels",Piyal Panapitiya,9786242041810,3.0
182,185,???? ?????? ?? ????????? ??????,His wesum lu ukussage abirahasa,"Spy,Child,Translations",Dayaa D. Fonseka,9786245941957,4.0
183,186,??????????? ????,Surupiniyage maranaya,"Spy,Translations,Novels",Gayan Sampath Waniganeththi,9789553131201,5.0
184,187,??? ?? ????????,Diya yata wikramaya,"Spy,Translations,Novels",Wasantha Pigera,9786246451752,5.0

In [45]:
pickle.dump(pt,open('pt.pkl','wb'))
pickle.dump(books,open('books.pkl','wb'))
pickle.dump(similarity_scores,open('similarity_scores.pkl','wb'))

# Recommend book by interested category

In [46]:
books['Category'].unique()

array(['Translations,Novels', 'Novels', 'Biographie,Novels',
       'Novels,Adventure,Child', 'Novels,Child', 'Novels,Fiction',
       'Child', 'Novels,Historical', 'Novels,Crime,Adventure',
       'Novels,Adventure', 'Biographies,Novels',
       'Translations,Novels,Adventure,Child', 'Short stories',
       'Novels, Adventure,Child', 'Translations,Novels,Adventure',
       'Translations,Sci-Fi,Novels', 'Spy,Translations,Novels',
       'Spy,Novels', 'Translations,Spy,Novels', 'Mystrey,Novels',
       'Mystrey,Translations,Novels', 'Spy,Novels,Mystrey',
       'Child,Educational', 'Translations,Child', 'Child,Spy',
       'Translations,Novels,Child', 'Translations,Short-Stories',
       'Spy,Child,Translations'], dtype=object)

In [47]:
def recommend_by_category(category):
    temp_df = books[books['Category'] == category]
    return temp_df[['Book_Title','Author','Category']]

In [48]:
recommend_by_category('Novels')

                  Book_Title                                  Author Category
1              Dandumonaraya                   Martin Wickramasinghe   Novels
2        May mara prasangaya                Mahinda prasad masimbula   Novels
3               Manikkawatha                Mahinda prasad masimbula   Novels
6                 Baeddegama                          Leonard Woolf    Novels
7            Karuwala gedara                   Martin Wickramasinghe   Novels
8                  Senkottan                Mahinda prasad masimbula   Novels
10            Golu Hadawatha                     Karunasena Jayalath   Novels
13             Forget me not              Charitha Prawardhi Bandara   Novels
16              Nil katarolu                    Tharanga Dissanayake   Novels
18                  Pethsama                         Leel Gunasekara   Novels
19               Rathu ahasa                   Sakunthala Kumarihami   Novels
20              Maagamsoliya                      Mohan Raj Madawala   Novels
22          Wassana Sihinaya                 Upul shantha sannasgala   Novels
23    Duppathun nathi lokaya                        G. B. Senanayake   Novels
24                Kaliyugaya                   Martin Wickramasinghe   Novels
25                   Loveena  Somasiri Munasinghe,Mohan Raj Madawala   Novels
26               Sinimurukku                          Kasun Mahendra   Novels
31        Thubasaka wilapaya                 Upul shantha sannasgala   Novels
71           Pattabhishekaya                      Indumathi Jayasena   Novels
72             Dhawala pilli                         Nishadini Alwis   Novels
73                Wade kella               Shammi pahalagamaarachchi   Novels
74                Rel Gedara                   Isuri Dahara De Silva   Novels
75        Sahathika aeththak                         Durendra indika   Novels
77               Nil erabadu                   Harshani Samarathunga   Novels
78            Sanda yahana-2                       Ruwani liyangolla   Novels
79               Katu mathin                       Pransika fernando   Novels
80                      Kalu                  Isuru hidella arachchi   Novels
81              Wiyali kopul                        Sanjali liyanage   Novels
82               Katu mathin                       Pransika fernando   Novels
83             Diriya puthek            Wasantha kumudini kannangara   Novels
84               Amuthu dige                        Prasila godahewa   Novels
85                    Giraya                          Cyril c perera   Novels
86                Chandragni             Darshana shammi wijethilaka   Novels
87                 Dusswapna                        Palitha jayakodi   Novels
88             Bodili yamaya                        Saman Athapatthu   Novels
89            Jasmin suwanda                        Lalith Nishantha   Novels
90   Sithe ketunu dewanagara                         P.B. Jayasekara   Novels
91            Marijuana king                         Sahan Lakshitha   Novels
92       Sath siyak siyapath                     Chiranji Ranathunga   Novels
93           Senehebara ruth               Manel Jayanthi Gunasekara   Novels
94      Heta amawakada sekai             Achala dilrukshi marasinghe   Novels
95                    Maulee                     Shanthi dissanayake   Novels
96             Allapu gedara               Randika Kadawathaarachchi   Novels
97            Thittha kaduru                      Roshan rathnappuli   Novels
98           Ethera gangawen                         Kamani wathsala   Novels
99        Bawanthara bandana                       Thilaka kudahetti   Novels
100             Wiyali kopul                        Sanjali Liyanage   Novels

In [49]:
users.head()

,user id,name,age,gender,liked categories
0,1,Udari,25-34,Female,"Novels,Sci-Fi,Adventure"
1,2,Isuru,25-34,Male,"Translations,Novels,Adventure,Child"
2,3,Buddhi Ekanayake,25-34,Male,"Spy,Novels,Crime"
3,4,R.P.D.Lakshan,18-24,Male,"Mystrey,Biographie"
4,5,Dileka,18-24,Female,"Novels,Sci-Fi,Adventure"

In [50]:
from sklearn.impute import SimpleImputer
import pandas as pd
import numpy as np

# Sample data
data = {
    'age': ['25-34', '35-44', np.nan, '18-24'],
    'gender': ['Male', 'Female', 'Male', np.nan],
    'rating': [5, 4, np.nan, 3]
}

df = pd.DataFrame(data)

# Separate numeric and non-numeric columns
numeric_cols = df.select_dtypes(include=[np.number]).columns
non_numeric_cols = df.select_dtypes(exclude=[np.number]).columns

# Impute numeric columns with mean
imputer_numeric = SimpleImputer(strategy='mean')
df[numeric_cols] = imputer_numeric.fit_transform(df[numeric_cols])

# Impute non-numeric columns with most frequent
imputer_non_numeric = SimpleImputer(strategy='most_frequent')
df[non_numeric_cols] = imputer_non_numeric.fit_transform(df[non_numeric_cols])

print(df)

     age  gender  rating
0  25-34    Male     5.0
1  35-44  Female     4.0
2  18-24    Male     4.0
3  18-24    Male     3.0

In [51]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from scipy.sparse import csr_matrix
from sklearn.neighbors import NearestNeighbors
import numpy as np

# Load the data
ratings = pd.read_csv('dataset/ratings.csv')
books = pd.read_csv('dataset/books.csv')
users = pd.read_csv('dataset/users.csv')

# Preprocess the data
ratings = ratings.dropna()
ratings['Ratings'] = ratings['Ratings'].astype(float)

# Aggregate ratings to ensure unique combinations of User-ID and ISBN
ratings = ratings.groupby(['User-ID', 'ISBN']).agg({'Ratings': 'mean'}).reset_index()

# Create the user-item matrix
user_item_matrix = ratings.pivot(index='User-ID', columns='ISBN', values='Ratings').fillna(0)
user_item_matrix_sparse = csr_matrix(user_item_matrix.values)

# Train the model using Nearest Neighbors
model_knn = NearestNeighbors(metric='cosine', algorithm='brute')
model_knn.fit(user_item_matrix_sparse)

# Function to make book recommendations
def recommend_books(user_id, n_recommendations=5):
    user_index = user_item_matrix.index.get_loc(user_id)
    distances, indices = model_knn.kneighbors(user_item_matrix.iloc[user_index, :].values.reshape(1, -1), n_neighbors=n_recommendations+1)
    recommendations = []
    for i in range(1, len(distances.flatten())):
        book_index = user_item_matrix.columns[indices.flatten()[i]]
        book_title = books[books['ISBN'] == book_index]['Book_Title'].values[0]
        recommendations.append(book_title)
    return recommendations

# Example usage
user_id = 1
print(f"Recommendations for user {user_id}: {recommend_books(user_id)}")

Recommendations for user 1: ['Chaura Rajina', 'Baeddegama', 'Sinimurukku', 'Maagamsoliya', 'Indraneela manikya']

In [52]:
!pip install scikit-surprise

Requirement already satisfied: scikit-surprise in c:\dev\python\lib\site-packages (1.1.4)
Requirement already satisfied: joblib>=1.2.0 in c:\dev\python\lib\site-packages (from scikit-surprise) (1.3.2)
Requirement already satisfied: numpy>=1.19.5 in c:\dev\python\lib\site-packages (from scikit-surprise) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in c:\dev\python\lib\site-packages (from scikit-surprise) (1.11.2)

WARNING: Ignoring invalid distribution ~pencv-python-headless (C:\Dev\Python\Lib\site-packages)
WARNING: Ignoring invalid distribution ~pencv-python-headless (C:\Dev\Python\Lib\site-packages)
WARNING: Ignoring invalid distribution ~pencv-python-headless (C:\Dev\Python\Lib\site-packages)

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [53]:
import pandas as pd
from surprise import Dataset, Reader, SVD
from surprise.model_selection import train_test_split
from surprise import accuracy

# Load the data
ratings = pd.read_csv('dataset/ratings.csv')

# Prepare the data for Surprise
reader = Reader(rating_scale=(1, 5))
data = Dataset.load_from_df(ratings[['User-ID', 'ISBN', 'Ratings']], reader)

# Split the data into training and test sets
trainset, testset = train_test_split(data, test_size=0.25)

# Train the SVD model
model = SVD()
model.fit(trainset)

In [54]:
# Evaluate the model
predictions = model.test(testset)
accuracy.rmse(predictions)

RMSE: 1.3548

1.3547507031581087

# Make a prediction for the test user